"""init

Revision ID: 162c15a3b4a4
Revises: 
Create Date: 2023-05-19 22:40:28.617698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162c15a3b4a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.String(length=1024), nullable=True),
    sa.Column('answer', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
